Repository cheqd/cheqd-node, pull requests merged in 2021-11, with the labels that each got.

#175 Separate MsgWriteRequest into two requests
  proto/cheqd/common.proto
  proto/cheqd/did.proto
  proto/cheqd/genesis.proto
  proto/cheqd/query.proto
  proto/cheqd/stateValue.proto
  proto/cheqd/tx.proto
  x/cheqd/handler.go
  x/cheqd/keeper/msg_server_did.go
  x/cheqd/tests/handler_test.go
  x/cheqd/tests/handler_test_setup.go
  x/cheqd/types/codec.go
  x/cheqd/types/common.pb.go
  x/cheqd/types/did.pb.go
  x/cheqd/types/genesis.pb.go
  x/cheqd/types/messages.go
  x/cheqd/types/messages_did.go
  x/cheqd/types/messages_write_request.go
  x/cheqd/types/msg_test.go
  x/cheqd/types/query.pb.go
  x/cheqd/types/stateValue.go
  x/cheqd/types/stateValue.pb.go
  x/cheqd/types/tx.pb.go
Labels: hacktoberfest-accepted

#176 Import and Export DID Genesis
  proto/cheqd/genesis.proto
  x/cheqd/genesis.go
  x/cheqd/keeper/did.go
  x/cheqd/types/genesis.go
  x/cheqd/types/genesis.pb.go
Labels: hacktoberfest-accepted

#179 renamed proto ServiceEndpoint to Service
  proto/cheqd/did.proto
  proto/cheqd/query.proto
  proto/cheqd/tx.proto
  x/cheqd/tests/handler_test.go
  x/cheqd/tests/handler_test_setup.go
  x/cheqd/types/did.pb.go
  x/cheqd/types/messages_did.go
  x/cheqd/types/msg_test.go
  x/cheqd/types/query.pb.go
  x/cheqd/types/tx.pb.go
Labels: hacktoberfest-accepted

#178 Save namespace into state
  proto/cheqd/genesis.proto
  x/cheqd/genesis.go
  x/cheqd/keeper/config.go
  x/cheqd/keeper/msg_server_did.go
  x/cheqd/keeper/utils.go
  x/cheqd/tests/handler_test_setup.go
  x/cheqd/types/genesis.go
  x/cheqd/types/genesis.pb.go
  x/cheqd/types/keys.go
Labels: hacktoberfest-accepted

#185 Get rid of symlinks and add ability to change HOME directory
  build_tools/postinst
  docs/deb-package-overview.md
  docs/setting-up-a-new-node.md
Labels: devops

#143 Add DIDDoc to Identity ADR
  SUMMARY.md
  architecture/adr-list/README.md
  architecture/adr-list/adr-001-payment-mechanism-for-issuing-credentials.md
  architecture/adr-list/adr-002-cheqd-did-method.md
  architecture/adr-list/adr-003-cli-tools.md
  architecture/adr-list/adr-004-token-fractions.md
  architecture/adr-list/adr-005-genesis-parameters.md
  architecture/adr-list/adr-006-community-tax.md
  architecture/adr-list/adr-007-revocation-registry.md
  architecture/adr-list/adr-template.md
  architecture/adr-list/adr_002_identity_transactions.md
  docs/identity-api.md
Labels: hacktoberfest-accepted, adr

#174 Add swagger docs
  docs/swagger.yaml
Labels: hacktoberfest-accepted
